<a href="https://colab.research.google.com/github/PyCraftMusadaq/TensorFlowCodes/blob/main/00_Pytorch_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensors

In [ ]:
# scalers
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
type(scaler)

torch.Tensor

In [ ]:
# regular integer back from tensor
type(scaler.item())

int

In [ ]:
# vector
vector = torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([5])

In [ ]:
MATRIX = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
MATRIX,MATRIX.shape,MATRIX.ndim

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]),
 2)

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
 [4,5,6],
  [7,8,9]]])
TENSOR,TENSOR.shape,TENSOR.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#Creating Random Tensors using Pytorch

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0562, 0.3287, 0.9974, 0.6024],
        [0.6785, 0.1695, 0.8050, 0.5028],
        [0.1323, 0.8788, 0.3267, 0.5947]])

In [ ]:
## create a random tensor with similar shape to image
image_tensor = torch.rand(size=(224,224,3))
image_tensor

tensor([[[0.8213, 0.8962, 0.1089],
         [0.4571, 0.9779, 0.1489],
         [0.0973, 0.0163, 0.8376],
         ...,
         [0.1295, 0.3728, 0.7951],
         [0.7178, 0.7223, 0.7639],
         [0.8971, 0.3104, 0.9325]],

        [[0.5332, 0.4174, 0.6069],
         [0.6190, 0.9479, 0.8088],
         [0.4000, 0.7916, 0.7990],
         ...,
         [0.7960, 0.7659, 0.7991],
         [0.1139, 0.2752, 0.2639],
         [0.7166, 0.9180, 0.7560]],

        [[0.5696, 0.5082, 0.4776],
         [0.1712, 0.1551, 0.2095],
         [0.0815, 0.3831, 0.8234],
         ...,
         [0.0152, 0.9101, 0.2335],
         [0.9349, 0.5491, 0.7927],
         [0.1168, 0.0337, 0.1112]],

        ...,

        [[0.4780, 0.8068, 0.2891],
         [0.5106, 0.6906, 0.9715],
         [0.8509, 0.4328, 0.4379],
         ...,
         [0.3503, 0.1822, 0.3351],
         [0.8041, 0.7683, 0.0616],
         [0.0516, 0.3735, 0.5090]],

        [[0.6818, 0.6683, 0.2114],
         [0.5533, 0.6959, 0.6252],
         [0.

In [ ]:
image_tensor.shape,image_tensor.ndim,image_tensor.size

(torch.Size([224, 224, 3]), 3, <function Tensor.size>)

##Zeros and ones tensors

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(5,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor.dtype

torch.float32

## createing a tensors with range and tensors-like

In [ ]:
# torch.range
torch.range(0,10) # don't use it

<ipython-input-11-24ca51d35b19>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(start=0,end=100,step=5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [ ]:
#tensor_like is used to replicate the shape of some other tensors
zeros_tensors = torch.zeros_like(input=ones)

In [ ]:
zeros_tensors

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
Tensor_datatypes = torch.tensor([3.0,4.0,5.0],dtype=None)
Tensor_datatypes.dtype

torch.float32

In [ ]:
Tensor_datatypes = torch.tensor([3.0,4.0,5.0],dtype=torch.float64,device=None,requires_grad=False) # require grad mean whether or not to track gradients while doing tensor operations.
Tensor_datatypes.dtype

torch.float64

##Getting information about tensors

In [ ]:
float_16_tensor = torch.tensor([1,2,3],dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
float_32_tensor = torch.tensor([1,2,3],dtype=torch.float32)
float_32_tensor

tensor([1., 2., 3.])

In [ ]:
result = float_16_tensor * float_32_tensor

In [ ]:
result.dtype

torch.float32

In [ ]:
int_tensor = torch.tensor([1,2,3])
int_tensor.dtype

torch.int64

In [ ]:
int_tensor*float_32_tensor

tensor([1., 4., 9.])

In [ ]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4839, 0.9222, 0.0403, 0.2434],
        [0.1233, 0.1610, 0.2123, 0.8895],
        [0.6389, 0.0049, 0.0372, 0.4426]])

In [ ]:
# find out detail about some_tensor
print(some_tensor)
print(f"DateType of Tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.4839, 0.9222, 0.0403, 0.2434],
        [0.1233, 0.1610, 0.2123, 0.8895],
        [0.6389, 0.0049, 0.0372, 0.4426]])
DateType of Tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


## Manipulating Tensors

In [ ]:
tensor = torch.tensor([1,2,3,4,5])
tensor+10

tensor([11, 12, 13, 14, 15])

In [ ]:
# Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30, 40, 50])

In [ ]:
torch.add(tensor,20)

tensor([21, 22, 23, 24, 25])

In [ ]:
torch.sub(tensor,10)

tensor([-9, -8, -7, -6, -5])

In [ ]:
# comparing the speed value
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(55)
CPU times: user 3.29 ms, sys: 0 ns, total: 3.29 ms
Wall time: 3.19 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.24 ms, sys: 22 µs, total: 1.26 ms
Wall time: 1.16 ms


tensor(55)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1230, 0.3384, 0.1646],
        [0.1341, 0.3330, 0.2222],
        [0.0682, 0.1285, 0.1612]])

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

In [ ]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
tensor_A.shape,tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

# Reshaping,stacking,,squeezing and unsqueezing tensors

In [ ]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# Add single dimension
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# change the view of x
z = x.view(1,9)
z,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked_1 = torch.stack([x,x,x,x],dim=1)
x_stacked_1

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked.T

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x = torch.rand(1,2)
x.ndim

2

In [ ]:
x.squeeze()

tensor([0.2539, 0.4310])

In [ ]:
x.squeeze().shape

torch.Size([2])

In [ ]:
x = torch.rand(1,1,2,1,9)
x,x.shape

(tensor([[[[[0.0898, 0.7955, 0.8090, 0.1411, 0.1600, 0.4459, 0.1291, 0.1163,
             0.4256]],
 
           [[0.9055, 0.7147, 0.4519, 0.7046, 0.1607, 0.1089, 0.0919, 0.1046,
             0.9475]]]]]),
 torch.Size([1, 1, 2, 1, 9]))

In [ ]:
x.squeeze()

tensor([[0.0898, 0.7955, 0.8090, 0.1411, 0.1600, 0.4459, 0.1291, 0.1163, 0.4256],
        [0.9055, 0.7147, 0.4519, 0.7046, 0.1607, 0.1089, 0.0919, 0.1046, 0.9475]])

In [ ]:
x.squeeze().shape

torch.Size([2, 9])

In [ ]:
# add a single dimension to a target tensor
x = torch.rand(9)

In [ ]:
x

tensor([0.7878, 0.6848, 0.5834, 0.3572, 0.8807, 0.9656, 0.5836, 0.6524, 0.1306])

In [ ]:
x.unsqueeze(dim=0)

tensor([[0.7878, 0.6848, 0.5834, 0.3572, 0.8807, 0.9656, 0.5836, 0.6524, 0.1306]])

In [ ]:
x,x.shape

(tensor([0.7878, 0.6848, 0.5834, 0.3572, 0.8807, 0.9656, 0.5836, 0.6524, 0.1306]),
 torch.Size([9]))

In [ ]:
x.unsqueeze(dim=1)

tensor([[0.7878],
        [0.6848],
        [0.5834],
        [0.3572],
        [0.8807],
        [0.9656],
        [0.5836],
        [0.6524],
        [0.1306]])

In [ ]:
x.unsqueeze(dim=1).shape

torch.Size([9, 1])

In [ ]:
x = torch.rand(2,3,5)
x

tensor([[[0.6678, 0.3747, 0.2680, 0.8896, 0.5306],
         [0.9140, 0.3814, 0.3930, 0.3299, 0.1522],
         [0.5759, 0.2146, 0.9331, 0.5320, 0.4602]],

        [[0.2858, 0.9956, 0.6784, 0.4791, 0.2444],
         [0.4079, 0.2059, 0.5825, 0.9878, 0.9260],
         [0.6734, 0.5663, 0.3864, 0.5058, 0.3012]]])

In [ ]:
x.size()

torch.Size([2, 3, 5])

In [ ]:
x_permuted = x.permute(2,0,1)
x_permuted

tensor([[[0.6678, 0.9140, 0.5759],
         [0.2858, 0.4079, 0.6734]],

        [[0.3747, 0.3814, 0.2146],
         [0.9956, 0.2059, 0.5663]],

        [[0.2680, 0.3930, 0.9331],
         [0.6784, 0.5825, 0.3864]],

        [[0.8896, 0.3299, 0.5320],
         [0.4791, 0.9878, 0.5058]],

        [[0.5306, 0.1522, 0.4602],
         [0.2444, 0.9260, 0.3012]]])

In [ ]:
x_permuted.shape

torch.Size([5, 2, 3])

In [ ]:
x_orignal = torch.rand(224,224,3)
x_permuted = x_orignal.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x_orignal[0,0,0] = 100
x_orignal[0].shape

torch.Size([224, 3])

In [ ]:
x_orignal[0,0,0]

tensor(100.)

In [ ]:
x_orignal

tensor([[[1.0000e+02, 5.2434e-02, 4.4071e-01],
         [2.9724e-01, 8.6409e-01, 5.5818e-01],
         [7.0417e-01, 2.2648e-01, 8.5184e-01],
         ...,
         [2.7182e-01, 5.8145e-01, 3.4486e-01],
         [4.9919e-01, 8.5483e-01, 2.4076e-01],
         [6.8300e-01, 3.1458e-01, 4.1392e-01]],

        [[9.7314e-02, 3.2438e-01, 3.5391e-01],
         [5.0851e-01, 7.1135e-01, 7.8794e-01],
         [3.5778e-01, 5.1945e-02, 7.1141e-01],
         ...,
         [2.5710e-01, 6.1342e-01, 2.0433e-01],
         [4.4653e-02, 2.2145e-02, 1.1849e-01],
         [5.6551e-01, 3.2567e-01, 1.2965e-01]],

        [[3.7273e-01, 5.2871e-01, 2.1965e-01],
         [6.1980e-01, 1.2104e-01, 6.9613e-02],
         [5.9391e-01, 1.7201e-01, 9.8843e-01],
         ...,
         [3.7363e-01, 6.0409e-01, 1.9188e-01],
         [9.7266e-01, 5.3468e-01, 2.2893e-01],
         [8.2737e-01, 5.7449e-01, 3.9303e-01]],

        ...,

        [[3.4001e-01, 4.5270e-01, 1.7190e-01],
         [3.9582e-01, 6.3403e-01, 2.4200e-02]

In [ ]:
x_permuted[0,0,0]

tensor(100.)

# indexing in pytorch

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# lets index on 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
# last number 9
x[:,2,2] # we can use semicolon to select all of target dimension.

tensor([9])

PyTorch Tensors & Numpy

In [ ]:
tensor = torch.rand(5,2)
tensor

tensor([[0.1233, 0.1030],
        [0.1645, 0.9227],
        [0.4186, 0.9764],
        [0.9885, 0.9518],
        [0.5476, 0.2942]])

In [ ]:
tensor.numpy()

array([[0.12330931, 0.10302716],
       [0.16453135, 0.9227224 ],
       [0.41856366, 0.97638637],
       [0.9884796 , 0.95177436],
       [0.5475738 , 0.29424214]], dtype=float32)

In [ ]:
type(tensor)

torch.Tensor

#Reproducbility(trying to take random out of random)

In [ ]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A,random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

# Accessing the GPU in Pytorch

In [2]:
torch.cuda.is_available()

True

In [3]:
# Device Agnostic Code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#count the number of devices of gpu's avaiable
torch.cuda.device_count()

1

# Putting tensors on GPU (defaul on CPU)

In [5]:
# create a tensor
tensor = torch.tensor([1,2,3,4,5])
tensor

tensor([1, 2, 3, 4, 5])

In [6]:
tensor.device

device(type='cpu')

In [7]:
# Move tensor  to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5], device='cuda:0')

### Moving tensors Back to CPU

In [8]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu

tensor([1, 2, 3, 4, 5])

In [9]:
tensor_on_cpu.device

device(type='cpu')