<a href="https://colab.research.google.com/github/PyCraftMusadaq/TensorFlowCodes/blob/main/00_Pytorch_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cpu


In [6]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensors

In [9]:
# scalers
scaler = torch.tensor(7)
scaler

tensor(7)

In [10]:
scaler.ndim

0

In [11]:
type(scaler)

torch.Tensor

In [12]:
# regular integer back from tensor
type(scaler.item())

int

In [13]:
# vector
vector = torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([5])

In [16]:
MATRIX = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
MATRIX,MATRIX.shape,MATRIX.ndim

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]),
 2)

In [17]:
TENSOR = torch.tensor([[[1,2,3],
 [4,5,6],
  [7,8,9]]])
TENSOR,TENSOR.shape,TENSOR.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#Creating Random Tensors using Pytorch

In [9]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0562, 0.3287, 0.9974, 0.6024],
        [0.6785, 0.1695, 0.8050, 0.5028],
        [0.1323, 0.8788, 0.3267, 0.5947]])

In [4]:
## create a random tensor with similar shape to image
image_tensor = torch.rand(size=(224,224,3))
image_tensor

tensor([[[0.8213, 0.8962, 0.1089],
         [0.4571, 0.9779, 0.1489],
         [0.0973, 0.0163, 0.8376],
         ...,
         [0.1295, 0.3728, 0.7951],
         [0.7178, 0.7223, 0.7639],
         [0.8971, 0.3104, 0.9325]],

        [[0.5332, 0.4174, 0.6069],
         [0.6190, 0.9479, 0.8088],
         [0.4000, 0.7916, 0.7990],
         ...,
         [0.7960, 0.7659, 0.7991],
         [0.1139, 0.2752, 0.2639],
         [0.7166, 0.9180, 0.7560]],

        [[0.5696, 0.5082, 0.4776],
         [0.1712, 0.1551, 0.2095],
         [0.0815, 0.3831, 0.8234],
         ...,
         [0.0152, 0.9101, 0.2335],
         [0.9349, 0.5491, 0.7927],
         [0.1168, 0.0337, 0.1112]],

        ...,

        [[0.4780, 0.8068, 0.2891],
         [0.5106, 0.6906, 0.9715],
         [0.8509, 0.4328, 0.4379],
         ...,
         [0.3503, 0.1822, 0.3351],
         [0.8041, 0.7683, 0.0616],
         [0.0516, 0.3735, 0.5090]],

        [[0.6818, 0.6683, 0.2114],
         [0.5533, 0.6959, 0.6252],
         [0.

In [5]:
image_tensor.shape,image_tensor.ndim,image_tensor.size

(torch.Size([224, 224, 3]), 3, <function Tensor.size>)

##Zeros and ones tensors

In [6]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
ones = torch.ones(size=(5,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
random_tensor.dtype

torch.float32

## createing a tensors with range and tensors-like

In [11]:
# torch.range
torch.range(0,10) # don't use it

<ipython-input-11-24ca51d35b19>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
torch.arange(start=0,end=100,step=5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [16]:
#tensor_like is used to replicate the shape of some other tensors
zeros_tensors = torch.zeros_like(input=ones)

In [17]:
zeros_tensors

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
Tensor_datatypes = torch.tensor([3.0,4.0,5.0],dtype=None)
Tensor_datatypes.dtype

torch.float32

In [20]:
Tensor_datatypes = torch.tensor([3.0,4.0,5.0],dtype=torch.float64,device=None,requires_grad=False) # require grad mean whether or not to track gradients while doing tensor operations.
Tensor_datatypes.dtype

torch.float64